import { JsonField } from '../types';

export const airForceArmedRegulation: JsonField[] = [
  { id: '1', name: 'Drill Commands & Movements', type: 'section_header', penalty: false },
  { id: '2', name: 'Forward March (ENTER)', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '3', name: 'Inspection, Port, Order Arms', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '4', name: 'Report In (VERBAL)', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '5', name: 'Parade Rest', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '6', name: 'Attention', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '7', name: '15-COUNT MANUAL ARMS', type: 'number', maxValue: 28, pointValue: 28, penalty: false },
  { id: '8', name: 'Count Off', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '9', name: 'Open Ranks', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '10', name: 'Close Ranks', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '11', name: 'Left Step March / Flight Halt', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '12', name: 'Left Face', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '13', name: 'Right Step March / FLIGHT HALT', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '14', name: 'About Face', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '15', name: 'Right Shoulder Arms', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '16', name: 'Forward March', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '17', name: 'Column Right March (Forward Mch)', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '18', name: 'FLIGHT HALT', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '19', name: 'Port Arms', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '20', name: 'Column Left March (Forward Mch)', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '21', name: 'FLIGHT HALT / Order Arms', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '22', name: 'Report Out (VERBAL)', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '23', name: 'Depart the Drill Floor', type: 'number', maxValue: 7, pointValue: 7, penalty: false },
  { id: '24', name: 'Penalties', type: 'section_header', penalty: false },
  { id: '25', name: 'Boundary Violations', type: 'text', penalty: false },
  { id: '26', name: 'Incorrect Commands', type: 'text', penalty: false },
  { id: '27', name: 'Pause Violations', type: 'text', penalty: false },
  { id: '28', name: 'Uniform Violations - Minor', type: 'text', penalty: false },
  { id: '29', name: 'Uniform Violations - Major', type: 'text', penalty: false },
  { id: '30', name: 'Technical Impression', type: 'text', penalty: false },
  { id: '31', name: 'Precision Impression', type: 'text', penalty: false }
];