-- Add remaining Lucide icons - Part 3 (Final Q-Z icons)
INSERT INTO public.icons (name, category, description) VALUES
-- Q-Z Icons
('QrCode', 'technology', 'QR code'),
('Quote', 'typography', 'Quote symbol'),
('Rabbit', 'animals', 'Rabbit'),
('Radar', 'technology', 'Radar'),
('Radiation', 'science', 'Radiation symbol'),
('Radical', 'math', 'Radical symbol'),
('RadioReceiver', 'technology', 'Radio receiver'),
('RadioTower', 'technology', 'Radio tower'),
('Radius', 'geometry', 'Radius'),
('RailSymbol', 'transportation', 'Rail symbol'),
('Rainbow', 'weather', 'Rainbow'),
('Rat', 'animals', 'Rat'),
('Ratio', 'math', 'Ratio'),
('Receipt', 'commerce', 'Receipt'),
('ReceiptCent', 'commerce', 'Receipt with cent'),
('ReceiptEuro', 'commerce', 'Receipt with euro'),
('ReceiptIndianRupee', 'commerce', 'Receipt with rupee'),
('ReceiptJapaneseYen', 'commerce', 'Receipt with yen'),
('ReceiptPoundSterling', 'commerce', 'Receipt with pound'),
('ReceiptRussianRuble', 'commerce', 'Receipt with ruble'),
('ReceiptSwissFranc', 'commerce', 'Receipt with franc'),
('ReceiptText', 'commerce', 'Text receipt'),
('ReceiptTurkishLira', 'commerce', 'Receipt with lira'),
('RectangleCircle', 'shapes', 'Rectangle with circle'),
('RectangleEllipsis', 'shapes', 'Rectangle with ellipsis'),
('RectangleGoggles', 'shapes', 'Rectangle goggles'),
('RectangleHorizontal', 'shapes', 'Horizontal rectangle'),
('RectangleVertical', 'shapes', 'Vertical rectangle'),
('Recycle', 'misc', 'Recycle symbol'),
('Redo', 'actions', 'Redo action'),
('Redo2', 'actions', 'Redo variant'),
('RedoDot', 'actions', 'Redo with dot'),
('RefreshCcwDot', 'actions', 'Refresh CCW with dot'),
('RefreshCwOff', 'actions', 'Refresh CW off'),
('Refrigerator', 'objects', 'Refrigerator'),
('Regex', 'technology', 'Regular expression'),
('RemoveFormatting', 'typography', 'Remove formatting'),
('Repeat2', 'media', 'Repeat variant'),
('Replace', 'actions', 'Replace'),
('ReplaceAll', 'actions', 'Replace all'),
('Reply', 'communication', 'Reply'),
('ReplyAll', 'communication', 'Reply all'),
('Ribbon', 'objects', 'Ribbon'),
('Rocket', 'misc', 'Rocket'),
('RockingChair', 'furniture', 'Rocking chair'),
('RollerCoaster', 'misc', 'Roller coaster'),
('Rose', 'plants', 'Rose flower'),
('Rotate3d', 'actions', '3D rotate'),
('RotateCcwKey', 'actions', 'Rotate CCW key'),
('RotateCcwSquare', 'actions', 'Rotate CCW square'),
('RotateCwSquare', 'actions', 'Rotate CW square'),
('Route', 'navigation', 'Route'),
('RouteOff', 'navigation', 'Route off'),
('Router', 'technology', 'Network router'),
('Rows2', 'layout', '2 rows'),
('Rows3', 'layout', '3 rows'),
('Rows4', 'layout', '4 rows'),
('RulerDimensionLine', 'tools', 'Ruler dimension line'),
('RussianRuble', 'commerce', 'Russian ruble'),
('Sailboat', 'transportation', 'Sailboat'),
('Salad', 'food', 'Salad'),
('Sandwich', 'food', 'Sandwich'),
('Satellite', 'technology', 'Satellite'),
('SatelliteDish', 'technology', 'Satellite dish'),
('SaudiRiyal', 'commerce', 'Saudi riyal'),
('SaveAll', 'actions', 'Save all'),
('SaveOff', 'actions', 'Save off'),
('Scale', 'objects', 'Scale balance'),
('Scale3d', 'misc', '3D scale'),
('Scaling', 'misc', 'Scaling'),
('Scan', 'technology', 'Scan'),
('ScanBarcode', 'technology', 'Scan barcode'),
('ScanEye', 'technology', 'Scan eye'),
('ScanFace', 'technology', 'Scan face'),
('ScanHeart', 'technology', 'Scan heart'),
('ScanLine', 'technology', 'Scan line'),
('ScanQrCode', 'technology', 'Scan QR code'),
('ScanSearch', 'technology', 'Scan search'),
('ScanText', 'technology', 'Scan text'),
('School', 'education', 'School building'),
('ScissorsLineDashed', 'tools', 'Scissors line dashed'),
('ScreenShare', 'technology', 'Screen share'),
('ScreenShareOff', 'technology', 'Screen share off'),
('Scroll', 'objects', 'Scroll'),
('ScrollText', 'objects', 'Scroll with text'),
('SearchCheck', 'actions', 'Search with check'),
('SearchCode', 'actions', 'Search code'),
('SearchSlash', 'actions', 'Search with slash'),
('SearchX', 'actions', 'Search with X'),
('Section', 'misc', 'Section'),
('SendHorizontal', 'actions', 'Send horizontal'),
('SendToBack', 'design', 'Send to back'),
('SeparatorHorizontal', 'layout', 'Horizontal separator'),
('SeparatorVertical', 'layout', 'Vertical separator'),
('ServerCog', 'technology', 'Server with settings'),
('ServerCrash', 'technology', 'Server crash'),
('ServerOff', 'technology', 'Server off'),
('Settings2', 'navigation', 'Settings variant'),
('Shapes', 'design', 'Shapes'),
('Sheet', 'objects', 'Sheet'),
('Shell', 'objects', 'Shell'),
('ShieldAlert', 'security', 'Shield with alert'),
('ShieldBan', 'security', 'Shield ban'),
('ShieldCheck', 'security', 'Shield with check'),
('ShieldEllipsis', 'security', 'Shield with ellipsis'),
('ShieldHalf', 'security', 'Half shield'),
('ShieldMinus', 'security', 'Shield with minus'),
('ShieldPlus', 'security', 'Shield with plus'),
('ShieldQuestionMark', 'security', 'Shield with question'),
('ShieldUser', 'security', 'Shield with user'),
('ShieldX', 'security', 'Shield with X'),
('Ship', 'transportation', 'Ship'),
('ShipWheel', 'transportation', 'Ship wheel'),
('Shirt', 'objects', 'Shirt'),
('ShoppingBasket', 'commerce', 'Shopping basket'),
('Shovel', 'tools', 'Shovel'),
('ShowerHead', 'objects', 'Shower head'),
('Shredder', 'objects', 'Paper shredder'),
('Shrimp', 'food', 'Shrimp'),
('Shrink', 'actions', 'Shrink'),
('Shrub', 'plants', 'Shrub'),
('Sigma', 'math', 'Sigma symbol'),
('Signal', 'technology', 'Signal strength'),
('SignalHigh', 'technology', 'High signal'),
('SignalLow', 'technology', 'Low signal'),
('SignalMedium', 'technology', 'Medium signal'),
('SignalZero', 'technology', 'No signal'),
('Signature', 'misc', 'Signature'),
('Signpost', 'misc', 'Signpost'),
('SignpostBig', 'misc', 'Large signpost'),
('Siren', 'objects', 'Emergency siren'),
('Skull', 'misc', 'Skull'),
('Slice', 'actions', 'Slice'),
('SlidersHorizontal', 'misc', 'Horizontal sliders'),
('SlidersVertical', 'misc', 'Vertical sliders'),
('SmartphoneCharging', 'technology', 'Charging smartphone'),
('SmartphoneNfc', 'technology', 'NFC smartphone'),
('SmilePlus', 'emoji', 'Smile with plus'),
('Snail', 'animals', 'Snail'),
('Snowflake', 'weather', 'Snowflake'),
('SoapDispenserDroplet', 'objects', 'Soap dispenser'),
('Sofa', 'furniture', 'Sofa'),
('Soup', 'food', 'Soup'),
('Space', 'misc', 'Space'),
('Spade', 'shapes', 'Spade suit'),
('Sparkle', 'misc', 'Sparkle'),
('Sparkles', 'misc', 'Multiple sparkles'),
('Speech', 'communication', 'Speech bubble'),
('SpellCheck', 'tools', 'Spell check'),
('SpellCheck2', 'tools', 'Spell check variant'),
('Spline', 'design', 'Spline curve'),
('SplinePointer', 'design', 'Spline with pointer'),
('Split', 'actions', 'Split'),
('Spool', 'objects', 'Thread spool'),
('Spotlight', 'objects', 'Spotlight'),
('SprayCan', 'tools', 'Spray can'),
('Sprout', 'plants', 'Plant sprout'),
('SquareActivity', 'shapes', 'Square with activity'),
('SquareArrowDown', 'arrows', 'Square arrow down'),
('SquareArrowDownLeft', 'arrows', 'Square arrow down left'),
('SquareArrowDownRight', 'arrows', 'Square arrow down right'),
('SquareArrowLeft', 'arrows', 'Square arrow left'),
('SquareArrowOutDownLeft', 'arrows', 'Square arrow out down left'),
('SquareArrowOutDownRight', 'arrows', 'Square arrow out down right'),
('SquareArrowOutUpLeft', 'arrows', 'Square arrow out up left'),
('SquareArrowOutUpRight', 'arrows', 'Square arrow out up right'),
('SquareArrowRight', 'arrows', 'Square arrow right'),
('SquareArrowUp', 'arrows', 'Square arrow up'),
('SquareArrowUpLeft', 'arrows', 'Square arrow up left'),
('SquareArrowUpRight', 'arrows', 'Square arrow up right'),
('SquareAsterisk', 'shapes', 'Square with asterisk'),
('SquareBottomDashedScissors', 'shapes', 'Square bottom dashed scissors'),
('SquareChartGantt', 'charts', 'Square Gantt chart'),
('SquareCheckBig', 'status', 'Large square check'),
('SquareChevronDown', 'arrows', 'Square chevron down'),
('SquareChevronLeft', 'arrows', 'Square chevron left'),
('SquareChevronRight', 'arrows', 'Square chevron right'),
('SquareChevronUp', 'arrows', 'Square chevron up'),
('SquareCode', 'technology', 'Square with code'),
('SquareDashed', 'shapes', 'Dashed square'),
('SquareDashedBottom', 'shapes', 'Square dashed bottom'),
('SquareDashedBottomCode', 'shapes', 'Square dashed bottom code'),
('SquareDashedKanban', 'shapes', 'Square dashed kanban'),
('SquareDashedMousePointer', 'shapes', 'Square dashed mouse pointer'),
('SquareDashedTopSolid', 'shapes', 'Square dashed top solid'),
('SquareDivide', 'math', 'Square with divide'),
('SquareDot', 'shapes', 'Square with dot'),
('SquareEqual', 'math', 'Square with equal'),
('SquareFunction', 'math', 'Square function'),
('SquareKanban', 'misc', 'Square kanban'),
('SquareLibrary', 'objects', 'Square library'),
('SquareM', 'typography', 'Square with M'),
('SquareMenu', 'navigation', 'Square menu'),
('SquareMinus', 'misc', 'Square with minus'),
('SquareMousePointer', 'misc', 'Square mouse pointer'),
('SquareParking', 'transportation', 'Square parking'),
('SquareParkingOff', 'transportation', 'Square parking off'),
('SquarePause', 'media', 'Square pause'),
('SquarePen', 'tools', 'Square with pen'),
('SquarePercent', 'math', 'Square with percent'),
('SquarePi', 'math', 'Square with pi'),
('SquarePilcrow', 'typography', 'Square with pilcrow'),
('SquarePlay', 'media', 'Square play'),
('SquarePlus', 'misc', 'Square with plus'),
('SquarePower', 'misc', 'Square power'),
('SquareRadical', 'math', 'Square radical'),
('SquareRoundCorner', 'shapes', 'Square round corner'),
('SquareScissors', 'tools', 'Square scissors'),
('SquareSigma', 'math', 'Square sigma'),
('SquareSlash', 'misc', 'Square with slash'),
('SquareSplitHorizontal', 'layout', 'Square split horizontal'),
('SquareSplitVertical', 'layout', 'Square split vertical'),
('SquareSquare', 'shapes', 'Nested squares'),
('SquareStack', 'layout', 'Square stack'),
('SquareStar', 'misc', 'Square with star'),
('SquareStop', 'media', 'Square stop'),
('SquareTerminal', 'technology', 'Square terminal'),
('SquareUser', 'people', 'Square with user'),
('SquareUserRound', 'people', 'Square with round user'),
('SquareX', 'status', 'Square with X'),
('SquaresExclude', 'shapes', 'Squares exclude'),
('SquaresIntersect', 'shapes', 'Squares intersect'),
('SquaresSubtract', 'shapes', 'Squares subtract'),
('SquaresUnite', 'shapes', 'Squares unite'),
('Squircle', 'shapes', 'Rounded square'),
('SquircleDashed', 'shapes', 'Dashed squircle'),
('Squirrel', 'animals', 'Squirrel'),
('Stamp', 'objects', 'Rubber stamp'),
('StarHalf', 'misc', 'Half star'),
('StarOff', 'misc', 'Star off'),
('StepBack', 'media', 'Step back'),
('StepForward', 'media', 'Step forward'),
('Stethoscope', 'medical', 'Stethoscope'),
('Sticker', 'objects', 'Sticker'),
('StickyNote', 'objects', 'Sticky note'),
('Store', 'commerce', 'Store building'),
('StretchHorizontal', 'design', 'Stretch horizontal'),
('StretchVertical', 'design', 'Stretch vertical'),
('Strikethrough', 'typography', 'Strikethrough text'),
('Subscript', 'typography', 'Subscript text'),
('SunDim', 'weather', 'Dim sun'),
('SunMedium', 'weather', 'Medium sun'),
('SunMoon', 'weather', 'Sun and moon'),
('SunSnow', 'weather', 'Sun with snow'),
('Superscript', 'typography', 'Superscript text'),
('SwatchBook', 'design', 'Swatch book'),
('SwissFranc', 'commerce', 'Swiss franc'),
('SwitchCamera', 'media', 'Switch camera'),
('Sword', 'objects', 'Sword'),
('Swords', 'objects', 'Crossed swords'),
('Syringe', 'medical', 'Syringe'),
('Table2', 'layout', 'Table variant'),
('TableCellsMerge', 'layout', 'Table cells merge'),
('TableCellsSplit', 'layout', 'Table cells split'),
('TableColumnsSplit', 'layout', 'Table columns split'),
('TableOfContents', 'misc', 'Table of contents'),
('TableProperties', 'layout', 'Table properties'),
('TableRowsSplit', 'layout', 'Table rows split'),
('TabletSmartphone', 'technology', 'Tablet with smartphone'),
('Tablets', 'medical', 'Medicine tablets'),
('Tags', 'misc', 'Multiple tags'),
('Tally1', 'misc', 'Tally mark 1'),
('Tally2', 'misc', 'Tally mark 2'),
('Tally3', 'misc', 'Tally mark 3'),
('Tally4', 'misc', 'Tally mark 4'),
('Tally5', 'misc', 'Tally mark 5'),
('Tangent', 'math', 'Tangent'),
('Telescope', 'science', 'Telescope'),
('Tent', 'objects', 'Camping tent'),
('TentTree', 'objects', 'Tent with tree'),
('TestTube', 'science', 'Test tube'),
('TestTubeDiagonal', 'science', 'Diagonal test tube'),
('TestTubes', 'science', 'Multiple test tubes'),
('Text', 'typography', 'Text'),
('TextCursor', 'typography', 'Text cursor'),
('TextCursorInput', 'typography', 'Text cursor input'),
('TextQuote', 'typography', 'Text quote'),
('TextSearch', 'typography', 'Text search'),
('TextSelect', 'typography', 'Text select'),
('Theater', 'objects', 'Theater'),
('ThermometerSnowflake', 'weather', 'Thermometer with snow'),
('ThermometerSun', 'weather', 'Thermometer with sun'),
('Ticket', 'objects', 'Ticket'),
('TicketCheck', 'objects', 'Ticket with check'),
('TicketMinus', 'objects', 'Ticket with minus'),
('TicketPercent', 'objects', 'Ticket with percent'),
('TicketPlus', 'objects', 'Ticket with plus'),
('TicketSlash', 'objects', 'Ticket with slash'),
('TicketX', 'objects', 'Ticket with X'),
('Tickets', 'objects', 'Multiple tickets'),
('TicketsPlane', 'transportation', 'Plane tickets'),
('Timer', 'time', 'Timer'),
('TimerOff', 'time', 'Timer off'),
('TimerReset', 'time', 'Timer reset'),
('ToggleLeft', 'misc', 'Toggle left'),
('ToggleRight', 'misc', 'Toggle right'),
('Toilet', 'objects', 'Toilet'),
('ToolCase', 'tools', 'Tool case'),
('Tornado', 'weather', 'Tornado'),
('Torus', 'shapes', 'Torus shape'),
('Touchpad', 'technology', 'Touchpad'),
('TouchpadOff', 'technology', 'Touchpad off'),
('TowerControl', 'transportation', 'Air traffic control tower'),
('ToyBrick', 'objects', 'Toy brick'),
('Tractor', 'transportation', 'Tractor'),
('TrafficCone', 'transportation', 'Traffic cone'),
('TrainFront', 'transportation', 'Train front'),
('TrainFrontTunnel', 'transportation', 'Train front tunnel'),
('TrainTrack', 'transportation', 'Train track'),
('TramFront', 'transportation', 'Tram front'),
('Transgender', 'people', 'Transgender symbol'),
('TreeDeciduous', 'plants', 'Deciduous tree'),
('TreePalm', 'plants', 'Palm tree'),
('TreePine', 'plants', 'Pine tree'),
('Trees', 'plants', 'Multiple trees'),
('Trello', 'social', 'Trello'),
('TrendingUpDown', 'charts', 'Trending up down'),
('TriangleAlert', 'status', 'Triangle alert'),
('TriangleDashed', 'shapes', 'Dashed triangle'),
('TriangleRight', 'shapes', 'Right triangle'),
('TruckElectric', 'transportation', 'Electric truck'),
('TurkishLira', 'commerce', 'Turkish lira'),
('Turntable', 'music', 'Turntable'),
('Turtle', 'animals', 'Turtle'),
('TvMinimal', 'technology', 'Minimal TV'),
('TvMinimalPlay', 'technology', 'Minimal TV with play'),
('TypeOutline', 'typography', 'Type outline'),
('UmbrellaOff', 'weather', 'Umbrella off'),
('Undo2', 'actions', 'Undo variant'),
('UndoDot', 'actions', 'Undo with dot'),
('UnfoldHorizontal', 'design', 'Unfold horizontal'),
('UnfoldVertical', 'design', 'Unfold vertical'),
('Ungroup', 'design', 'Ungroup'),
('University', 'education', 'University'),
('Unlink', 'misc', 'Unlink'),
('Unlink2', 'misc', 'Unlink variant'),
('Unplug', 'technology', 'Unplug'),
('Usb', 'technology', 'USB connector'),
('UserCheck', 'people', 'User with check'),
('UserCog', 'people', 'User with settings'),
('UserLock', 'people', 'User with lock'),
('UserMinus', 'people', 'User with minus'),
('UserPen', 'people', 'User with pen'),
('UserPlus', 'people', 'User with plus'),
('UserRound', 'people', 'Round user'),
('UserRoundCheck', 'people', 'Round user with check'),
('UserRoundCog', 'people', 'Round user with settings'),
('UserRoundMinus', 'people', 'Round user with minus'),
('UserRoundPen', 'people', 'Round user with pen'),
('UserRoundPlus', 'people', 'Round user with plus'),
('UserRoundSearch', 'people', 'Round user search'),
('UserRoundX', 'people', 'Round user with X'),
('UserSearch', 'people', 'User search'),
('UserStar', 'people', 'User with star'),
('UserX', 'people', 'User with X'),
('UsersRound', 'people', 'Round users'),
('Utensils', 'food', 'Utensils'),
('UtensilsCrossed', 'food', 'Crossed utensils'),
('UtilityPole', 'objects', 'Utility pole'),
('Variable', 'technology', 'Variable'),
('Vault', 'security', 'Vault'),
('VectorSquare', 'shapes', 'Vector square'),
('Vegan', 'food', 'Vegan symbol'),
('VenetianMask', 'objects', 'Venetian mask'),
('Venus', 'misc', 'Venus planet'),
('VenusAndMars', 'misc', 'Venus and Mars'),
('Vibrate', 'technology', 'Vibrate'),
('VibrateOff', 'technology', 'Vibrate off'),
('VideoOff', 'media', 'Video off'),
('Videotape', 'media', 'Videotape'),
('View', 'misc', 'View'),
('Volleyball', 'sports', 'Volleyball'),
('VolumeOff', 'media', 'Volume off'),
('Vote', 'misc', 'Vote'),
('Wallet', 'commerce', 'Wallet'),
('WalletCards', 'commerce', 'Wallet with cards'),
('WalletMinimal', 'commerce', 'Minimal wallet'),
('Wallpaper', 'design', 'Wallpaper'),
('Wand', 'tools', 'Magic wand'),
('WandSparkles', 'tools', 'Wand with sparkles'),
('Warehouse', 'construction', 'Warehouse'),
('WashingMachine', 'objects', 'Washing machine'),
('Waves', 'nature', 'Waves'),
('WavesLadder', 'nature', 'Waves ladder'),
('Waypoints', 'navigation', 'Waypoints'),
('Webcam', 'technology', 'Webcam'),
('Webhook', 'technology', 'Webhook'),
('WebhookOff', 'technology', 'Webhook off'),
('Weight', 'objects', 'Weight'),
('Wheat', 'food', 'Wheat'),
('WheatOff', 'food', 'No wheat'),
('WholeWord', 'typography', 'Whole word'),
('WifiCog', 'technology', 'WiFi with settings'),
('WifiHigh', 'technology', 'High WiFi'),
('WifiLow', 'technology', 'Low WiFi'),
('WifiPen', 'technology', 'WiFi with pen'),
('WifiSync', 'technology', 'WiFi sync'),
('WifiZero', 'technology', 'No WiFi'),
('WindArrowDown', 'weather', 'Wind arrow down'),
('Wine', 'food', 'Wine glass'),
('WineOff', 'food', 'No wine'),
('Workflow', 'misc', 'Workflow'),
('Worm', 'animals', 'Worm'),
('WrapText', 'typography', 'Wrap text'),
('ZoomOut', 'misc', 'Zoom out')

ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  updated_at = now();