-- Add remaining Lucide icons in batches - Part 1 (G-Z icons)
INSERT INTO public.icons (name, category, description) VALUES
-- G-L Icons
('GalleryHorizontal', 'layout', 'Horizontal gallery'),
('GalleryHorizontalEnd', 'layout', 'Horizontal gallery end'),
('GalleryThumbnails', 'layout', 'Gallery thumbnails'),
('GalleryVertical', 'layout', 'Vertical gallery'),
('GalleryVerticalEnd', 'layout', 'Vertical gallery end'),
('Gamepad', 'games', 'Game controller'),
('Gamepad2', 'games', 'Game controller variant'),
('Gauge', 'misc', 'Gauge meter'),
('Gavel', 'objects', 'Judge gavel'),
('Gem', 'objects', 'Precious gem'),
('GeorgianLari', 'commerce', 'Georgian lari currency'),
('Ghost', 'misc', 'Ghost'),
('GitBranchPlus', 'technology', 'Git branch with plus'),
('GitCommitHorizontal', 'technology', 'Git commit horizontal'),
('GitCommitVertical', 'technology', 'Git commit vertical'),
('GitCompare', 'technology', 'Git compare'),
('GitCompareArrows', 'technology', 'Git compare with arrows'),
('GitFork', 'technology', 'Git fork'),
('GitGraph', 'technology', 'Git graph'),
('GitPullRequestArrow', 'technology', 'Pull request with arrow'),
('GitPullRequestClosed', 'technology', 'Closed pull request'),
('GitPullRequestCreate', 'technology', 'Create pull request'),
('GitPullRequestCreateArrow', 'technology', 'Create pull request with arrow'),
('GitPullRequestDraft', 'technology', 'Draft pull request'),
('GlassWater', 'food', 'Glass of water'),
('Glasses', 'objects', 'Eyeglasses'),
('GlobeLock', 'misc', 'Globe with lock'),
('Goal', 'sports', 'Goal target'),
('Gpu', 'technology', 'Graphics processing unit'),
('GraduationCap', 'education', 'Graduation cap'),
('Grape', 'food', 'Grape fruit'),
('Grid2x2', 'layout', '2x2 grid'),
('Grid2x2Check', 'layout', '2x2 grid with check'),
('Grid2x2Plus', 'layout', '2x2 grid with plus'),
('Grid2x2X', 'layout', '2x2 grid with X'),
('Grid3x2', 'layout', '3x2 grid'),
('Grid3x3', 'layout', '3x3 grid'),
('Grip', 'misc', 'Grip handle'),
('GripHorizontal', 'misc', 'Horizontal grip'),
('GripVertical', 'misc', 'Vertical grip'),
('Group', 'misc', 'Group'),
('Guitar', 'music', 'Guitar instrument'),
('Ham', 'food', 'Ham meat'),
('Hamburger', 'food', 'Hamburger'),
('Hammer', 'tools', 'Hammer tool'),
('Hand', 'people', 'Hand'),
('HandCoins', 'commerce', 'Hand with coins'),
('HandFist', 'people', 'Clenched fist'),
('HandGrab', 'people', 'Grabbing hand'),
('HandHeart', 'people', 'Hand with heart'),
('HandHelping', 'people', 'Helping hand'),
('HandMetal', 'people', 'Rock hand sign'),
('HandPlatter', 'people', 'Hand with platter'),
('Handbag', 'objects', 'Handbag'),
('Handshake', 'people', 'Handshake'),
('HardDriveDownload', 'technology', 'Hard drive download'),
('HardDriveUpload', 'technology', 'Hard drive upload'),
('HardHat', 'safety', 'Hard hat'),
('HatGlasses', 'objects', 'Hat with glasses'),
('Haze', 'weather', 'Hazy weather'),
('HdmiPort', 'technology', 'HDMI port'),
('Heading', 'typography', 'Heading text'),
('Heading1', 'typography', 'Heading 1'),
('Heading2', 'typography', 'Heading 2'),
('Heading3', 'typography', 'Heading 3'),
('Heading4', 'typography', 'Heading 4'),
('Heading5', 'typography', 'Heading 5'),
('Heading6', 'typography', 'Heading 6'),
('HeadphoneOff', 'media', 'Headphone off'),
('Headset', 'technology', 'Headset'),
('HeartCrack', 'misc', 'Broken heart'),
('HeartHandshake', 'people', 'Heart handshake'),
('HeartMinus', 'misc', 'Heart with minus'),
('HeartOff', 'misc', 'Heart off'),
('HeartPlus', 'misc', 'Heart with plus'),
('HeartPulse', 'medical', 'Heart pulse'),
('Heater', 'objects', 'Heater'),
('Highlighter', 'tools', 'Text highlighter'),
('History', 'misc', 'History'),
('Hop', 'misc', 'Hop'),
('HopOff', 'misc', 'Hop off'),
('Hospital', 'medical', 'Hospital building'),
('Hotel', 'objects', 'Hotel building'),
('Hourglass', 'time', 'Hourglass timer'),
('House', 'construction', 'House'),
('HousePlug', 'construction', 'House with plug'),
('HousePlus', 'construction', 'House with plus'),
('HouseWifi', 'construction', 'House with wifi'),
('IceCreamBowl', 'food', 'Ice cream bowl'),
('IceCreamCone', 'food', 'Ice cream cone'),
('IdCard', 'objects', 'ID card'),
('IdCardLanyard', 'objects', 'ID card with lanyard'),
('ImageDown', 'media', 'Image download'),
('ImageMinus', 'media', 'Image with minus'),
('ImageOff', 'media', 'Image off'),
('ImagePlay', 'media', 'Image with play'),
('ImagePlus', 'media', 'Image with plus'),
('ImageUp', 'media', 'Image upload'),
('ImageUpscale', 'media', 'Image upscale'),
('Images', 'media', 'Multiple images'),
('Import', 'actions', 'Import'),
('IndentDecrease', 'typography', 'Decrease indent'),
('IndentIncrease', 'typography', 'Increase indent'),
('IndianRupee', 'commerce', 'Indian rupee'),
('Infinity', 'math', 'Infinity symbol'),
('InspectionPanel', 'misc', 'Inspection panel'),
('IterationCcw', 'misc', 'Iteration counter-clockwise'),
('IterationCw', 'misc', 'Iteration clockwise'),
('JapaneseYen', 'commerce', 'Japanese yen'),
('Joystick', 'games', 'Joystick controller'),
('Kanban', 'misc', 'Kanban board'),
('Kayak', 'sports', 'Kayak boat'),
('KeyRound', 'security', 'Round key'),
('KeySquare', 'security', 'Square key'),
('KeyboardMusic', 'music', 'Music keyboard'),
('KeyboardOff', 'technology', 'Keyboard off'),
('Lamp', 'objects', 'Table lamp'),
('LampCeiling', 'objects', 'Ceiling lamp'),
('LampDesk', 'objects', 'Desk lamp'),
('LampFloor', 'objects', 'Floor lamp'),
('LampWallDown', 'objects', 'Wall lamp down'),
('LampWallUp', 'objects', 'Wall lamp up'),
('LandPlot', 'misc', 'Land plot'),
('Landmark', 'misc', 'Landmark'),
('Languages', 'misc', 'Languages'),
('Laptop', 'technology', 'Laptop computer'),
('LaptopMinimal', 'technology', 'Minimal laptop'),
('LaptopMinimalCheck', 'technology', 'Laptop with check'),
('Lasso', 'tools', 'Lasso tool'),
('LassoSelect', 'tools', 'Lasso select tool'),
('Laugh', 'emoji', 'Laughing face'),
('Layers2', 'design', 'Layers variant'),
('LayoutDashboard', 'layout', 'Dashboard layout'),
('LayoutGrid', 'layout', 'Grid layout'),
('LayoutList', 'layout', 'List layout'),
('LayoutPanelLeft', 'layout', 'Left panel layout'),
('LayoutPanelTop', 'layout', 'Top panel layout'),
('LayoutTemplate', 'layout', 'Template layout'),
('Leaf', 'plants', 'Leaf'),
('LeafyGreen', 'plants', 'Leafy green'),
('Lectern', 'objects', 'Lectern'),
('LetterText', 'typography', 'Letter text'),
('Library', 'objects', 'Library'),
('LibraryBig', 'objects', 'Large library'),
('Ligature', 'typography', 'Text ligature'),
('Lightbulb', 'objects', 'Light bulb'),
('LightbulbOff', 'objects', 'Light bulb off'),
('LineSquiggle', 'shapes', 'Squiggly line'),
('Link2Off', 'misc', 'Link 2 off'),
('ListCheck', 'misc', 'List with check'),
('ListChecks', 'misc', 'List with multiple checks'),
('ListCollapse', 'misc', 'Collapse list'),
('ListEnd', 'misc', 'List end'),
('ListFilter', 'misc', 'Filter list'),
('ListFilterPlus', 'misc', 'Filter list with plus'),
('ListMinus', 'misc', 'List with minus'),
('ListMusic', 'music', 'Music list'),
('ListOrdered', 'misc', 'Ordered list'),
('ListPlus', 'misc', 'List with plus'),
('ListRestart', 'misc', 'Restart list'),
('ListStart', 'misc', 'Start list'),
('ListTodo', 'misc', 'Todo list'),
('ListTree', 'misc', 'Tree list'),
('ListVideo', 'media', 'Video list'),
('ListX', 'misc', 'List with X'),
('LoaderCircle', 'misc', 'Circular loader'),
('LoaderPinwheel', 'misc', 'Pinwheel loader'),
('Locate', 'navigation', 'Locate'),
('LocateFixed', 'navigation', 'Fixed location'),
('LocateOff', 'navigation', 'Location off'),
('LockKeyhole', 'security', 'Lock with keyhole'),
('LockKeyholeOpen', 'security', 'Open lock with keyhole'),
('LockOpen', 'security', 'Open lock'),
('LogIn', 'navigation', 'Log in'),
('LogOut', 'navigation', 'Log out'),
('Logs', 'technology', 'System logs'),
('Lollipop', 'food', 'Lollipop candy'),
('Luggage', 'objects', 'Travel luggage')

ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  updated_at = now();