-- Add all missing Lucide icons to the icons table
-- Converting kebab-case names to PascalCase for React compatibility

INSERT INTO public.icons (name, category, description) VALUES
-- A-B Icons
('AArrowDown', 'arrows', 'A with down arrow'),
('AArrowUp', 'arrows', 'A with up arrow'),
('ALargeSmall', 'typography', 'Font size indicator'),
('Accessibility', 'accessibility', 'Accessibility symbol'),
('AirVent', 'misc', 'Air vent'),
('AlarmClock', 'time', 'Alarm clock'),
('AlarmClockCheck', 'time', 'Alarm clock with check'),
('AlarmClockMinus', 'time', 'Alarm clock minus'),
('AlarmClockOff', 'time', 'Alarm clock off'),
('AlarmClockPlus', 'time', 'Alarm clock plus'),
('AlarmSmoke', 'alerts', 'Smoke alarm'),
('Album', 'media', 'Music album'),
('AlignCenterHorizontal', 'layout', 'Align center horizontally'),
('AlignCenterVertical', 'layout', 'Align center vertically'),
('AlignEndHorizontal', 'layout', 'Align end horizontally'),
('AlignEndVertical', 'layout', 'Align end vertically'),
('AlignHorizontalDistributeCenter', 'layout', 'Distribute horizontally center'),
('AlignHorizontalDistributeEnd', 'layout', 'Distribute horizontally end'),
('AlignHorizontalDistributeStart', 'layout', 'Distribute horizontally start'),
('AlignHorizontalJustifyCenter', 'layout', 'Justify horizontally center'),
('AlignHorizontalJustifyEnd', 'layout', 'Justify horizontally end'),
('AlignHorizontalJustifyStart', 'layout', 'Justify horizontally start'),
('AlignHorizontalSpaceAround', 'layout', 'Space around horizontally'),
('AlignHorizontalSpaceBetween', 'layout', 'Space between horizontally'),
('AlignStartHorizontal', 'layout', 'Align start horizontally'),
('AlignStartVertical', 'layout', 'Align start vertically'),
('AlignVerticalDistributeCenter', 'layout', 'Distribute vertically center'),
('AlignVerticalDistributeEnd', 'layout', 'Distribute vertically end'),
('AlignVerticalDistributeStart', 'layout', 'Distribute vertically start'),
('AlignVerticalJustifyCenter', 'layout', 'Justify vertically center'),
('AlignVerticalJustifyEnd', 'layout', 'Justify vertically end'),
('AlignVerticalJustifyStart', 'layout', 'Justify vertically start'),
('AlignVerticalSpaceAround', 'layout', 'Space around vertically'),
('AlignVerticalSpaceBetween', 'layout', 'Space between vertically'),
('Ambulance', 'transportation', 'Ambulance vehicle'),
('Ampersand', 'typography', 'Ampersand symbol'),
('Ampersands', 'typography', 'Multiple ampersands'),
('Amphora', 'objects', 'Ancient Greek jar'),
('Angry', 'emoji', 'Angry face'),
('Annoyed', 'emoji', 'Annoyed face'),
('Antenna', 'technology', 'Radio antenna'),
('Anvil', 'tools', 'Blacksmith anvil'),
('AppWindow', 'technology', 'Application window'),
('AppWindowMac', 'technology', 'Mac application window'),
('Apple', 'food', 'Apple fruit'),
('ArchiveRestore', 'files', 'Restore from archive'),
('ArchiveX', 'files', 'Archive with X'),
('Armchair', 'furniture', 'Comfortable chair'),
('ArrowBigDown', 'arrows', 'Large down arrow'),
('ArrowBigDownDash', 'arrows', 'Large down arrow with dash'),
('ArrowBigLeft', 'arrows', 'Large left arrow'),
('ArrowBigLeftDash', 'arrows', 'Large left arrow with dash'),
('ArrowBigRight', 'arrows', 'Large right arrow'),
('ArrowBigRightDash', 'arrows', 'Large right arrow with dash'),
('ArrowBigUp', 'arrows', 'Large up arrow'),
('ArrowBigUpDash', 'arrows', 'Large up arrow with dash'),
('ArrowDown01', 'arrows', 'Down arrow 0-1'),
('ArrowDown10', 'arrows', 'Down arrow 1-0'),
('ArrowDownAZ', 'arrows', 'Down arrow A-Z'),
('ArrowDownFromLine', 'arrows', 'Down arrow from line'),
('ArrowDownNarrowWide', 'arrows', 'Down arrow narrow to wide'),
('ArrowDownToDot', 'arrows', 'Down arrow to dot'),
('ArrowDownToLine', 'arrows', 'Down arrow to line'),
('ArrowDownUp', 'arrows', 'Down up arrows'),
('ArrowDownWideNarrow', 'arrows', 'Down arrow wide to narrow'),
('ArrowDownZA', 'arrows', 'Down arrow Z-A'),
('ArrowLeftFromLine', 'arrows', 'Left arrow from line'),
('ArrowLeftRight', 'arrows', 'Left right arrows'),
('ArrowLeftToLine', 'arrows', 'Left arrow to line'),
('ArrowRightFromLine', 'arrows', 'Right arrow from line'),
('ArrowRightLeft', 'arrows', 'Right left arrows'),
('ArrowRightToLine', 'arrows', 'Right arrow to line'),
('ArrowUp01', 'arrows', 'Up arrow 0-1'),
('ArrowUp10', 'arrows', 'Up arrow 1-0'),
('ArrowUpAZ', 'arrows', 'Up arrow A-Z'),
('ArrowUpDown', 'arrows', 'Up down arrows'),
('ArrowUpFromDot', 'arrows', 'Up arrow from dot'),
('ArrowUpFromLine', 'arrows', 'Up arrow from line'),
('ArrowUpNarrowWide', 'arrows', 'Up arrow narrow to wide'),
('ArrowUpToLine', 'arrows', 'Up arrow to line'),
('ArrowUpWideNarrow', 'arrows', 'Up arrow wide to narrow'),
('ArrowUpZA', 'arrows', 'Up arrow Z-A'),
('ArrowsUpFromLine', 'arrows', 'Multiple arrows up from line'),
('Asterisk', 'symbols', 'Asterisk symbol'),
('Atom', 'science', 'Atomic symbol'),
('AudioLines', 'media', 'Audio waveform lines'),
('AudioWaveform', 'media', 'Audio waveform'),
('Axe', 'tools', 'Wood cutting axe'),
('Axis3d', 'geometry', '3D coordinate axes'),

-- Badge and Alert Icons
('Baby', 'people', 'Baby icon'),
('Backpack', 'objects', 'Travel backpack'),
('BadgeAlert', 'status', 'Badge with alert'),
('BadgeCent', 'commerce', 'Badge with cent symbol'),
('BadgeCheck', 'status', 'Badge with checkmark'),
('BadgeDollarSign', 'commerce', 'Badge with dollar sign'),
('BadgeEuro', 'commerce', 'Badge with euro symbol'),
('BadgeIndianRupee', 'commerce', 'Badge with rupee symbol'),
('BadgeInfo', 'status', 'Badge with info'),
('BadgeJapaneseYen', 'commerce', 'Badge with yen symbol'),
('BadgeMinus', 'status', 'Badge with minus'),
('BadgePercent', 'commerce', 'Badge with percent'),
('BadgePlus', 'status', 'Badge with plus'),
('BadgePoundSterling', 'commerce', 'Badge with pound symbol'),
('BadgeQuestionMark', 'status', 'Badge with question mark'),
('BadgeRussianRuble', 'commerce', 'Badge with ruble symbol'),
('BadgeSwissFranc', 'commerce', 'Badge with franc symbol'),
('BadgeTurkishLira', 'commerce', 'Badge with lira symbol'),
('BadgeX', 'status', 'Badge with X'),
('BaggageClaim', 'transportation', 'Airport baggage claim'),
('Ban', 'status', 'Ban or prohibit symbol'),
('Banana', 'food', 'Banana fruit'),
('Bandage', 'medical', 'Medical bandage'),
('Banknote', 'commerce', 'Paper money'),
('BanknoteArrowDown', 'commerce', 'Money with down arrow'),
('BanknoteArrowUp', 'commerce', 'Money with up arrow'),
('BanknoteX', 'commerce', 'Money with X'),
('Barcode', 'commerce', 'Product barcode'),
('Barrel', 'objects', 'Storage barrel'),
('Baseline', 'typography', 'Text baseline'),
('Bath', 'objects', 'Bathtub'),
('BatteryFull', 'technology', 'Full battery'),
('BatteryLow', 'technology', 'Low battery'),
('BatteryMedium', 'technology', 'Medium battery'),
('BatteryPlus', 'technology', 'Battery with plus'),
('BatteryWarning', 'technology', 'Battery warning'),
('Beaker', 'science', 'Laboratory beaker'),
('Bean', 'food', 'Coffee bean'),
('BeanOff', 'food', 'No coffee bean'),
('Bed', 'furniture', 'Bed'),
('BedDouble', 'furniture', 'Double bed'),
('BedSingle', 'furniture', 'Single bed'),
('Beef', 'food', 'Beef meat'),
('Beer', 'food', 'Beer mug'),
('BeerOff', 'food', 'No beer'),
('BellDot', 'navigation', 'Bell with dot'),
('BellElectric', 'navigation', 'Electric bell'),
('BellMinus', 'navigation', 'Bell with minus'),
('BellPlus', 'navigation', 'Bell with plus'),
('BellRing', 'navigation', 'Ringing bell'),
('BetweenHorizontalEnd', 'layout', 'Between horizontal end'),
('BetweenHorizontalStart', 'layout', 'Between horizontal start'),
('BetweenVerticalEnd', 'layout', 'Between vertical end'),
('BetweenVerticalStart', 'layout', 'Between vertical start'),
('BicepsFlexed', 'people', 'Flexed biceps'),
('Bike', 'transportation', 'Bicycle'),
('Binary', 'technology', 'Binary code'),
('Binoculars', 'objects', 'Binoculars'),
('Biohazard', 'science', 'Biohazard symbol'),
('Bird', 'animals', 'Bird'),
('Bitcoin', 'commerce', 'Bitcoin cryptocurrency'),
('Blend', 'design', 'Blend tool'),
('Blinds', 'objects', 'Window blinds'),
('Blocks', 'objects', 'Building blocks'),
('BluetoothConnected', 'technology', 'Bluetooth connected'),
('BluetoothSearching', 'technology', 'Bluetooth searching'),
('Bolt', 'misc', 'Lightning bolt'),
('Bomb', 'objects', 'Explosive bomb'),
('Bone', 'medical', 'Bone'),
('BookA', 'files', 'Book with A'),
('BookAlert', 'files', 'Book with alert'),
('BookAudio', 'files', 'Audio book'),
('BookCheck', 'files', 'Book with check'),
('BookCopy', 'files', 'Book copy'),
('BookDashed', 'files', 'Dashed book'),
('BookDown', 'files', 'Book with down arrow'),
('BookHeadphones', 'files', 'Book with headphones'),
('BookHeart', 'files', 'Book with heart'),
('BookImage', 'files', 'Book with image'),
('BookKey', 'files', 'Book with key'),
('BookLock', 'files', 'Locked book'),
('BookMarked', 'files', 'Marked book'),
('BookMinus', 'files', 'Book with minus'),
('BookOpenCheck', 'files', 'Open book with check'),
('BookOpenText', 'files', 'Open book with text'),
('BookPlus', 'files', 'Book with plus'),
('BookText', 'files', 'Text book'),
('BookType', 'files', 'Typography book'),
('BookUp', 'files', 'Book with up arrow'),
('BookUp2', 'files', 'Book with up arrow variant'),
('BookUser', 'files', 'Book with user'),
('BookX', 'files', 'Book with X'),
('BookmarkCheck', 'files', 'Bookmark with check'),
('BookmarkMinus', 'files', 'Bookmark with minus'),
('BookmarkPlus', 'files', 'Bookmark with plus'),
('BookmarkX', 'files', 'Bookmark with X'),
('BoomBox', 'media', 'Boom box radio'),
('Bot', 'technology', 'Robot bot'),
('BotMessageSquare', 'technology', 'Bot with message'),
('BotOff', 'technology', 'Bot offline'),
('BottleWine', 'food', 'Wine bottle'),
('BowArrow', 'sports', 'Bow and arrow'),
('Boxes', 'objects', 'Multiple boxes'),
('Braces', 'typography', 'Curly braces'),
('Brackets', 'typography', 'Square brackets'),
('Brain', 'medical', 'Human brain'),
('BrainCircuit', 'technology', 'Brain with circuits'),
('BrainCog', 'technology', 'Brain with cog'),
('BrickWall', 'construction', 'Brick wall'),
('BrickWallFire', 'construction', 'Brick wall on fire'),
('BrickWallShield', 'construction', 'Protected brick wall'),
('BriefcaseBusiness', 'commerce', 'Business briefcase'),
('BriefcaseConveyorBelt', 'commerce', 'Briefcase on conveyor'),
('BriefcaseMedical', 'medical', 'Medical briefcase'),
('BringToFront', 'design', 'Bring to front'),
('BrushCleaning', 'tools', 'Cleaning brush'),
('Bubbles', 'misc', 'Soap bubbles'),
('Bug', 'technology', 'Software bug'),
('BugOff', 'technology', 'Bug off'),
('BugPlay', 'technology', 'Bug with play'),
('Building', 'construction', 'Building'),
('Building2', 'construction', 'Building variant'),
('Bus', 'transportation', 'Bus'),
('BusFront', 'transportation', 'Bus front view'),

-- C Icons
('Cable', 'technology', 'Electrical cable'),
('CableCar', 'transportation', 'Cable car'),
('Cake', 'food', 'Birthday cake'),
('CakeSlice', 'food', 'Cake slice'),
('Calculator', 'objects', 'Calculator'),
('Calendar1', 'time', 'Calendar day 1'),
('CalendarArrowDown', 'time', 'Calendar with down arrow'),
('CalendarArrowUp', 'time', 'Calendar with up arrow'),
('CalendarCheck2', 'time', 'Calendar with check variant'),
('CalendarClock', 'time', 'Calendar with clock'),
('CalendarCog', 'time', 'Calendar with settings'),
('CalendarDays', 'time', 'Calendar days'),
('CalendarFold', 'time', 'Folded calendar'),
('CalendarHeart', 'time', 'Calendar with heart'),
('CalendarMinus2', 'time', 'Calendar minus variant'),
('CalendarOff', 'time', 'Calendar off'),
('CalendarPlus2', 'time', 'Calendar plus variant'),
('CalendarRange', 'time', 'Calendar range'),
('CalendarSearch', 'time', 'Calendar search'),
('CalendarSync', 'time', 'Calendar sync'),
('CalendarX2', 'time', 'Calendar X variant'),
('CameraOff', 'media', 'Camera off'),
('Candy', 'food', 'Candy'),
('CandyCane', 'food', 'Candy cane'),
('CandyOff', 'food', 'No candy'),
('Cannabis', 'plants', 'Cannabis leaf'),
('Captions', 'media', 'Video captions'),
('CaptionsOff', 'media', 'Captions off'),
('Car', 'transportation', 'Car'),
('CarFront', 'transportation', 'Car front view'),
('CarTaxiFront', 'transportation', 'Taxi front view'),
('Caravan', 'transportation', 'Travel caravan'),
('CardSim', 'technology', 'SIM card'),
('Carrot', 'food', 'Carrot vegetable'),
('CaseLower', 'typography', 'Lowercase text'),
('CaseSensitive', 'typography', 'Case sensitive'),
('CaseUpper', 'typography', 'Uppercase text'),
('CassetteTape', 'media', 'Cassette tape'),
('Castle', 'construction', 'Medieval castle'),
('Cat', 'animals', 'Cat'),
('Cctv', 'security', 'CCTV camera'),
('ChartArea', 'charts', 'Area chart'),
('ChartBarBig', 'charts', 'Large bar chart'),
('ChartBarDecreasing', 'charts', 'Decreasing bar chart'),
('ChartBarIncreasing', 'charts', 'Increasing bar chart'),
('ChartBarStacked', 'charts', 'Stacked bar chart'),
('ChartCandlestick', 'charts', 'Candlestick chart'),
('ChartColumn', 'charts', 'Column chart'),
('ChartColumnBig', 'charts', 'Large column chart'),
('ChartColumnDecreasing', 'charts', 'Decreasing column chart'),
('ChartColumnIncreasing', 'charts', 'Increasing column chart'),
('ChartColumnStacked', 'charts', 'Stacked column chart'),
('ChartGantt', 'charts', 'Gantt chart'),
('ChartLine', 'charts', 'Line chart'),
('ChartNetwork', 'charts', 'Network chart'),
('ChartNoAxesColumn', 'charts', 'Column chart no axes'),
('ChartNoAxesColumnDecreasing', 'charts', 'Decreasing column no axes'),
('ChartNoAxesColumnIncreasing', 'charts', 'Increasing column no axes'),
('ChartNoAxesCombined', 'charts', 'Combined chart no axes'),
('ChartNoAxesGantt', 'charts', 'Gantt chart no axes'),
('ChartScatter', 'charts', 'Scatter plot'),
('ChartSpline', 'charts', 'Spline chart'),
('CheckCheck', 'status', 'Double check'),
('CheckLine', 'status', 'Check line'),
('ChefHat', 'food', 'Chef hat'),
('Cherry', 'food', 'Cherry fruit'),
('ChevronFirst', 'arrows', 'First chevron'),
('ChevronLast', 'arrows', 'Last chevron'),
('ChevronsDownUp', 'arrows', 'Chevrons down up'),
('ChevronsLeftRight', 'arrows', 'Chevrons left right'),
('ChevronsLeftRightEllipsis', 'arrows', 'Chevrons with ellipsis'),
('ChevronsRightLeft', 'arrows', 'Chevrons right left'),
('ChevronsUpDown', 'arrows', 'Chevrons up down'),
('Chromium', 'technology', 'Chromium browser'),
('Church', 'construction', 'Church building'),
('Cigarette', 'objects', 'Cigarette'),
('CigaretteOff', 'objects', 'No smoking'),
('CircleAlert', 'status', 'Circle with alert'),
('CircleArrowDown', 'arrows', 'Circle arrow down'),
('CircleArrowLeft', 'arrows', 'Circle arrow left'),
('CircleArrowOutDownLeft', 'arrows', 'Circle arrow out down left'),
('CircleArrowOutDownRight', 'arrows', 'Circle arrow out down right'),
('CircleArrowOutUpLeft', 'arrows', 'Circle arrow out up left'),
('CircleArrowOutUpRight', 'arrows', 'Circle arrow out up right'),
('CircleArrowRight', 'arrows', 'Circle arrow right'),
('CircleArrowUp', 'arrows', 'Circle arrow up'),
('CircleCheckBig', 'status', 'Large circle check'),
('CircleChevronDown', 'arrows', 'Circle chevron down'),
('CircleChevronLeft', 'arrows', 'Circle chevron left'),
('CircleChevronRight', 'arrows', 'Circle chevron right'),
('CircleChevronUp', 'arrows', 'Circle chevron up'),
('CircleDashed', 'shapes', 'Dashed circle'),
('CircleDivide', 'math', 'Circle with divide'),
('CircleDollarSign', 'commerce', 'Circle with dollar'),
('CircleDot', 'shapes', 'Circle with dot'),
('CircleDotDashed', 'shapes', 'Dashed circle dot'),
('CircleEllipsis', 'misc', 'Circle with ellipsis'),
('CircleEqual', 'math', 'Circle with equal'),
('CircleFadingArrowUp', 'arrows', 'Fading circle arrow up'),
('CircleFadingPlus', 'misc', 'Fading circle plus'),
('CircleGauge', 'misc', 'Circle gauge'),
('CircleMinus', 'misc', 'Circle with minus'),
('CircleOff', 'shapes', 'Circle off'),
('CircleParking', 'transportation', 'Parking circle'),
('CircleParkingOff', 'transportation', 'No parking circle'),
('CirclePause', 'media', 'Circle pause'),
('CirclePercent', 'math', 'Circle with percent'),
('CirclePlay', 'media', 'Circle play'),
('CirclePlus', 'misc', 'Circle with plus'),
('CirclePoundSterling', 'commerce', 'Circle with pound'),
('CirclePower', 'misc', 'Circle power'),
('CircleQuestionMark', 'status', 'Circle question mark'),
('CircleSlash', 'misc', 'Circle with slash'),
('CircleSlash2', 'misc', 'Circle slash variant'),
('CircleSmall', 'shapes', 'Small circle'),
('CircleStar', 'misc', 'Circle with star'),
('CircleStop', 'media', 'Circle stop'),
('CircleUser', 'people', 'Circle with user'),
('CircleUserRound', 'people', 'Circle with round user'),
('CircleX', 'status', 'Circle with X'),
('CircuitBoard', 'technology', 'Circuit board'),
('Citrus', 'food', 'Citrus fruit'),
('Clapperboard', 'media', 'Movie clapperboard'),
('ClipboardCheck', 'files', 'Clipboard with check'),
('ClipboardClock', 'files', 'Clipboard with clock'),
('ClipboardCopy', 'files', 'Clipboard copy'),
('ClipboardList', 'files', 'Clipboard list'),
('ClipboardMinus', 'files', 'Clipboard minus'),
('ClipboardPaste', 'files', 'Clipboard paste'),
('ClipboardPen', 'files', 'Clipboard pen'),
('ClipboardPenLine', 'files', 'Clipboard pen line'),
('ClipboardPlus', 'files', 'Clipboard plus'),
('ClipboardType', 'files', 'Clipboard type'),
('ClipboardX', 'files', 'Clipboard X'),
('Clock1', 'time', 'Clock 1 o\'clock'),
('Clock2', 'time', 'Clock 2 o\'clock'),
('Clock3', 'time', 'Clock 3 o\'clock'),
('Clock4', 'time', 'Clock 4 o\'clock'),
('Clock5', 'time', 'Clock 5 o\'clock'),
('Clock6', 'time', 'Clock 6 o\'clock'),
('Clock7', 'time', 'Clock 7 o\'clock'),
('Clock8', 'time', 'Clock 8 o\'clock'),
('Clock9', 'time', 'Clock 9 o\'clock'),
('Clock10', 'time', 'Clock 10 o\'clock'),
('Clock11', 'time', 'Clock 11 o\'clock'),
('Clock12', 'time', 'Clock 12 o\'clock'),
('ClockAlert', 'time', 'Clock with alert'),
('ClockArrowDown', 'time', 'Clock arrow down'),
('ClockArrowUp', 'time', 'Clock arrow up'),
('ClockFading', 'time', 'Fading clock'),
('ClockPlus', 'time', 'Clock with plus'),
('ClosedCaption', 'media', 'Closed captions'),
('CloudAlert', 'weather', 'Cloud with alert'),
('CloudCheck', 'weather', 'Cloud with check'),
('CloudCog', 'weather', 'Cloud with settings'),
('CloudDownload', 'files', 'Cloud download'),
('CloudFog', 'weather', 'Foggy cloud'),
('CloudHail', 'weather', 'Hail cloud'),
('CloudMoon', 'weather', 'Cloud with moon'),
('CloudMoonRain', 'weather', 'Cloud moon rain'),
('CloudOff', 'weather', 'Cloud off'),
('CloudRainWind', 'weather', 'Cloud rain wind'),
('CloudSun', 'weather', 'Cloud with sun'),
('CloudSunRain', 'weather', 'Cloud sun rain'),
('CloudUpload', 'files', 'Cloud upload'),
('Cloudy', 'weather', 'Cloudy weather'),
('Clover', 'plants', 'Four leaf clover'),
('Club', 'shapes', 'Club suit'),
('CodeXml', 'technology', 'XML code'),
('Cog', 'misc', 'Settings cog'),
('Coins', 'commerce', 'Stack of coins'),
('Columns2', 'layout', '2 columns'),
('Columns3', 'layout', '3 columns'),
('Columns3Cog', 'layout', '3 columns with settings'),
('Columns4', 'layout', '4 columns'),
('Combine', 'misc', 'Combine elements'),
('Component', 'design', 'Component'),
('Computer', 'technology', 'Desktop computer'),
('ConciergeBell', 'objects', 'Concierge bell'),
('Cone', 'shapes', 'Cone shape'),
('Construction', 'construction', 'Under construction'),
('Contact', 'people', 'Contact person'),
('ContactRound', 'people', 'Round contact'),
('Container', 'objects', 'Storage container'),
('Contrast', 'design', 'Contrast adjustment'),
('Cookie', 'food', 'Cookie'),
('CookingPot', 'food', 'Cooking pot'),
('CopyCheck', 'actions', 'Copy with check'),
('CopyMinus', 'actions', 'Copy with minus'),
('CopyPlus', 'actions', 'Copy with plus'),
('CopySlash', 'actions', 'Copy with slash'),
('CopyX', 'actions', 'Copy with X'),
('Copyleft', 'misc', 'Copyleft symbol'),
('Copyright', 'misc', 'Copyright symbol'),
('CornerDownLeft', 'arrows', 'Corner down left'),
('CornerDownRight', 'arrows', 'Corner down right'),
('CornerLeftDown', 'arrows', 'Corner left down'),
('CornerLeftUp', 'arrows', 'Corner left up'),
('CornerRightDown', 'arrows', 'Corner right down'),
('CornerRightUp', 'arrows', 'Corner right up'),
('CornerUpLeft', 'arrows', 'Corner up left'),
('CornerUpRight', 'arrows', 'Corner up right'),
('CreativeCommons', 'misc', 'Creative Commons'),
('Croissant', 'food', 'Croissant pastry'),
('Cross', 'shapes', 'Cross shape'),
('Crown', 'objects', 'Royal crown'),
('Cuboid', 'shapes', '3D cuboid'),
('CupSoda', 'food', 'Soda cup'),
('Currency', 'commerce', 'Currency symbol'),
('Cylinder', 'shapes', 'Cylinder shape'),

-- D-F Icons
('Dam', 'construction', 'Water dam'),
('DatabaseBackup', 'technology', 'Database backup'),
('DatabaseZap', 'technology', 'Database with lightning'),
('DecimalsArrowLeft', 'math', 'Decimals arrow left'),
('DecimalsArrowRight', 'math', 'Decimals arrow right'),
('Delete', 'actions', 'Delete'),
('Dessert', 'food', 'Dessert'),
('Diameter', 'geometry', 'Circle diameter'),
('Diamond', 'shapes', 'Diamond shape'),
('DiamondMinus', 'shapes', 'Diamond with minus'),
('DiamondPercent', 'shapes', 'Diamond with percent'),
('DiamondPlus', 'shapes', 'Diamond with plus'),
('Dice1', 'games', 'Dice showing 1'),
('Dice2', 'games', 'Dice showing 2'),
('Dice3', 'games', 'Dice showing 3'),
('Dice4', 'games', 'Dice showing 4'),
('Dice5', 'games', 'Dice showing 5'),
('Dice6', 'games', 'Dice showing 6'),
('Dices', 'games', 'Multiple dice'),
('Diff', 'technology', 'Code difference'),
('Disc2', 'media', 'Disc variant 2'),
('Disc3', 'media', 'Disc variant 3'),
('DiscAlbum', 'media', 'Album disc'),
('Divide', 'math', 'Division symbol'),
('Dna', 'science', 'DNA helix'),
('DnaOff', 'science', 'DNA off'),
('Dock', 'technology', 'Dock station'),
('Dog', 'animals', 'Dog'),
('DollarSign', 'commerce', 'Dollar sign'),
('Donut', 'food', 'Donut'),
('DoorClosed', 'objects', 'Closed door'),
('DoorClosedLocked', 'objects', 'Locked closed door'),
('DoorOpen', 'objects', 'Open door'),
('Dot', 'shapes', 'Dot point'),
('DraftingCompass', 'tools', 'Drafting compass'),
('Drama', 'misc', 'Drama masks'),
('Dribbble', 'social', 'Dribbble'),
('Drill', 'tools', 'Power drill'),
('Drone', 'technology', 'Flying drone'),
('Droplet', 'misc', 'Water droplet'),
('DropletOff', 'misc', 'No droplet'),
('Drum', 'music', 'Drum'),
('Drumstick', 'food', 'Chicken drumstick'),
('Dumbbell', 'sports', 'Dumbbell weight'),
('Ear', 'medical', 'Human ear'),
('EarOff', 'medical', 'Ear off'),
('Earth', 'misc', 'Planet Earth'),
('EarthLock', 'misc', 'Earth with lock'),
('Eclipse', 'weather', 'Solar eclipse'),
('Egg', 'food', 'Egg'),
('EggFried', 'food', 'Fried egg'),
('EggOff', 'food', 'No egg'),
('Ellipsis', 'misc', 'Horizontal ellipsis'),
('EllipsisVertical', 'misc', 'Vertical ellipsis'),
('Equal', 'math', 'Equal sign'),
('EqualApproximately', 'math', 'Approximately equal'),
('EqualNot', 'math', 'Not equal'),
('Eraser', 'tools', 'Eraser'),
('EthernetPort', 'technology', 'Ethernet port'),
('Euro', 'commerce', 'Euro currency'),
('Expand', 'actions', 'Expand'),
('ExternalLink', 'navigation', 'External link'),
('EyeClosed', 'misc', 'Closed eye'),
('Factory', 'construction', 'Factory building'),
('Fan', 'objects', 'Electric fan'),
('Feather', 'misc', 'Feather'),
('Fence', 'objects', 'Fence'),
('FerrisWheel', 'misc', 'Ferris wheel'),
('FileArchive', 'files', 'Archive file'),
('FileAudio', 'files', 'Audio file'),
('FileAudio2', 'files', 'Audio file variant'),
('FileAxis3d', 'files', '3D axis file'),
('FileBadge', 'files', 'File with badge'),
('FileBadge2', 'files', 'File badge variant'),
('FileBox', 'files', 'File box'),
('FileChartColumn', 'files', 'Column chart file'),
('FileChartColumnIncreasing', 'files', 'Increasing chart file'),
('FileChartLine', 'files', 'Line chart file'),
('FileChartPie', 'files', 'Pie chart file'),
('FileCheck2', 'files', 'File check variant'),
('FileClock', 'files', 'File with clock'),
('FileCode', 'files', 'Code file'),
('FileCode2', 'files', 'Code file variant'),
('FileCog', 'files', 'File with settings'),
('FileDiff', 'files', 'File difference'),
('FileDigit', 'files', 'File with digit'),
('FileDown', 'files', 'File download'),
('FileHeart', 'files', 'File with heart'),
('FileImage', 'files', 'Image file'),
('FileInput', 'files', 'File input'),
('FileJson', 'files', 'JSON file'),
('FileJson2', 'files', 'JSON file variant'),
('FileKey', 'files', 'File with key'),
('FileKey2', 'files', 'File key variant'),
('FileLock', 'files', 'Locked file'),
('FileLock2', 'files', 'File lock variant'),
('FileMinus', 'files', 'File with minus'),
('FileMinus2', 'files', 'File minus variant'),
('FileMusic', 'files', 'Music file'),
('FileOutput', 'files', 'File output'),
('FilePen', 'files', 'File with pen'),
('FilePenLine', 'files', 'File pen line'),
('FilePlay', 'files', 'File play'),
('FilePlus', 'files', 'File with plus'),
('FilePlus2', 'files', 'File plus variant'),
('FileQuestionMark', 'files', 'File with question'),
('FileScan', 'files', 'File scan'),
('FileSearch', 'files', 'File search'),
('FileSearch2', 'files', 'File search variant'),
('FileSliders', 'files', 'File with sliders'),
('FileSpreadsheet', 'files', 'Spreadsheet file'),
('FileStack', 'files', 'File stack'),
('FileSymlink', 'files', 'File symlink'),
('FileTerminal', 'files', 'Terminal file'),
('FileType', 'files', 'File type'),
('FileType2', 'files', 'File type variant'),
('FileUp', 'files', 'File upload'),
('FileUser', 'files', 'File with user'),
('FileVideoCamera', 'files', 'Video camera file'),
('FileVolume', 'files', 'Volume file'),
('FileVolume2', 'files', 'Volume file variant'),
('FileWarning', 'files', 'File with warning'),
('FileX', 'files', 'File with X'),
('FileX2', 'files', 'File X variant'),
('Files', 'files', 'Multiple files'),
('Fingerprint', 'security', 'Fingerprint'),
('FireExtinguisher', 'safety', 'Fire extinguisher'),
('Fish', 'animals', 'Fish'),
('FishOff', 'animals', 'No fish'),
('FishSymbol', 'symbols', 'Fish symbol'),
('FlagOff', 'misc', 'Flag off'),
('FlagTriangleLeft', 'misc', 'Triangle flag left'),
('FlagTriangleRight', 'misc', 'Triangle flag right'),
('Flame', 'misc', 'Flame'),
('FlameKindling', 'misc', 'Kindling flame'),
('Flashlight', 'tools', 'Flashlight'),
('FlashlightOff', 'tools', 'Flashlight off'),
('FlaskConical', 'science', 'Conical flask'),
('FlaskConicalOff', 'science', 'Conical flask off'),
('FlaskRound', 'science', 'Round flask'),
('FlipHorizontal', 'design', 'Flip horizontal'),
('FlipHorizontal2', 'design', 'Flip horizontal variant'),
('FlipVertical', 'design', 'Flip vertical'),
('FlipVertical2', 'design', 'Flip vertical variant'),
('Flower', 'plants', 'Flower'),
('Flower2', 'plants', 'Flower variant'),
('Focus', 'misc', 'Focus target'),
('FoldHorizontal', 'design', 'Fold horizontal'),
('FoldVertical', 'design', 'Fold vertical'),
('FolderArchive', 'files', 'Archive folder'),
('FolderCheck', 'files', 'Folder with check'),
('FolderClock', 'files', 'Folder with clock'),
('FolderClosed', 'files', 'Closed folder'),
('FolderCode', 'files', 'Code folder'),
('FolderCog', 'files', 'Folder with settings'),
('FolderDot', 'files', 'Folder with dot'),
('FolderDown', 'files', 'Folder down'),
('FolderGit', 'files', 'Git folder'),
('FolderGit2', 'files', 'Git folder variant'),
('FolderHeart', 'files', 'Folder with heart'),
('FolderInput', 'files', 'Folder input'),
('FolderKanban', 'files', 'Kanban folder'),
('FolderKey', 'files', 'Folder with key'),
('FolderLock', 'files', 'Locked folder'),
('FolderMinus', 'files', 'Folder with minus'),
('FolderOpen', 'files', 'Open folder'),
('FolderOpenDot', 'files', 'Open folder with dot'),
('FolderOutput', 'files', 'Folder output'),
('FolderPen', 'files', 'Folder with pen'),
('FolderRoot', 'files', 'Root folder'),
('FolderSearch', 'files', 'Folder search'),
('FolderSearch2', 'files', 'Folder search variant'),
('FolderSymlink', 'files', 'Folder symlink'),
('FolderSync', 'files', 'Folder sync'),
('FolderTree', 'files', 'Folder tree'),
('FolderUp', 'files', 'Folder up'),
('FolderX', 'files', 'Folder with X'),
('Folders', 'files', 'Multiple folders'),
('Footprints', 'misc', 'Footprints'),
('Forklift', 'transportation', 'Forklift'),
('Forward', 'media', 'Forward'),
('Frame', 'design', 'Frame'),
('Fuel', 'misc', 'Fuel'),
('Fullscreen', 'misc', 'Fullscreen'),
('Funnel', 'misc', 'Funnel'),
('FunnelPlus', 'misc', 'Funnel with plus'),
('FunnelX', 'misc', 'Funnel with X')

ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  updated_at = now();