-- Add remaining Lucide icons - Part 2 (M-Z icons)
INSERT INTO public.icons (name, category, description) VALUES
-- M-P Icons
('Magnet', 'objects', 'Magnet'),
('MailCheck', 'communication', 'Mail with check'),
('MailMinus', 'communication', 'Mail with minus'),
('MailOpen', 'communication', 'Open mail'),
('MailPlus', 'communication', 'Mail with plus'),
('MailQuestionMark', 'communication', 'Mail with question'),
('MailSearch', 'communication', 'Mail search'),
('MailWarning', 'communication', 'Mail with warning'),
('MailX', 'communication', 'Mail with X'),
('Mailbox', 'communication', 'Mailbox'),
('Mails', 'communication', 'Multiple mails'),
('MapMinus', 'navigation', 'Map with minus'),
('MapPinCheck', 'navigation', 'Map pin with check'),
('MapPinCheckInside', 'navigation', 'Map pin check inside'),
('MapPinHouse', 'navigation', 'Map pin with house'),
('MapPinMinus', 'navigation', 'Map pin with minus'),
('MapPinMinusInside', 'navigation', 'Map pin minus inside'),
('MapPinOff', 'navigation', 'Map pin off'),
('MapPinPen', 'navigation', 'Map pin with pen'),
('MapPinPlus', 'navigation', 'Map pin with plus'),
('MapPinPlusInside', 'navigation', 'Map pin plus inside'),
('MapPinX', 'navigation', 'Map pin with X'),
('MapPinXInside', 'navigation', 'Map pin X inside'),
('MapPinned', 'navigation', 'Pinned map'),
('MapPlus', 'navigation', 'Map with plus'),
('Mars', 'misc', 'Mars planet'),
('MarsStroke', 'misc', 'Mars with stroke'),
('Martini', 'food', 'Martini cocktail'),
('Maximize2', 'misc', 'Maximize variant'),
('Medal', 'objects', 'Medal award'),
('Megaphone', 'communication', 'Megaphone'),
('MegaphoneOff', 'communication', 'Megaphone off'),
('MemoryStick', 'technology', 'Memory stick'),
('Merge', 'misc', 'Merge'),
('MessageCircleCode', 'communication', 'Message circle with code'),
('MessageCircleDashed', 'communication', 'Dashed message circle'),
('MessageCircleHeart', 'communication', 'Message circle with heart'),
('MessageCircleMore', 'communication', 'Message circle more'),
('MessageCircleOff', 'communication', 'Message circle off'),
('MessageCirclePlus', 'communication', 'Message circle plus'),
('MessageCircleQuestionMark', 'communication', 'Message circle question'),
('MessageCircleReply', 'communication', 'Message circle reply'),
('MessageCircleWarning', 'communication', 'Message circle warning'),
('MessageCircleX', 'communication', 'Message circle X'),
('MessageSquareCode', 'communication', 'Message square with code'),
('MessageSquareDashed', 'communication', 'Dashed message square'),
('MessageSquareDiff', 'communication', 'Message square diff'),
('MessageSquareDot', 'communication', 'Message square dot'),
('MessageSquareHeart', 'communication', 'Message square heart'),
('MessageSquareLock', 'communication', 'Locked message square'),
('MessageSquareMore', 'communication', 'Message square more'),
('MessageSquareOff', 'communication', 'Message square off'),
('MessageSquarePlus', 'communication', 'Message square plus'),
('MessageSquareQuote', 'communication', 'Message square quote'),
('MessageSquareReply', 'communication', 'Message square reply'),
('MessageSquareShare', 'communication', 'Message square share'),
('MessageSquareText', 'communication', 'Message square text'),
('MessageSquareWarning', 'communication', 'Message square warning'),
('MessageSquareX', 'communication', 'Message square X'),
('MessagesSquare', 'communication', 'Multiple message squares'),
('MicOff', 'media', 'Microphone off'),
('MicVocal', 'media', 'Vocal microphone'),
('Microchip', 'technology', 'Microchip'),
('Microscope', 'science', 'Microscope'),
('Microwave', 'objects', 'Microwave oven'),
('Milestone', 'misc', 'Milestone'),
('Milk', 'food', 'Milk'),
('MilkOff', 'food', 'No milk'),
('Minimize2', 'misc', 'Minimize variant'),
('MonitorCheck', 'technology', 'Monitor with check'),
('MonitorCog', 'technology', 'Monitor with settings'),
('MonitorDot', 'technology', 'Monitor with dot'),
('MonitorDown', 'technology', 'Monitor down'),
('MonitorOff', 'technology', 'Monitor off'),
('MonitorPause', 'technology', 'Monitor pause'),
('MonitorPlay', 'technology', 'Monitor play'),
('MonitorSmartphone', 'technology', 'Monitor with smartphone'),
('MonitorSpeaker', 'technology', 'Monitor with speaker'),
('MonitorStop', 'technology', 'Monitor stop'),
('MonitorUp', 'technology', 'Monitor up'),
('MonitorX', 'technology', 'Monitor X'),
('MoonStar', 'weather', 'Moon with star'),
('Mountain', 'nature', 'Mountain'),
('MountainSnow', 'nature', 'Snow mountain'),
('Mouse', 'technology', 'Computer mouse'),
('MouseOff', 'technology', 'Mouse off'),
('MousePointer2', 'misc', 'Mouse pointer variant'),
('MousePointerBan', 'misc', 'Banned mouse pointer'),
('MousePointerClick', 'misc', 'Clicking mouse pointer'),
('Move3d', 'misc', '3D move'),
('MoveDiagonal', 'misc', 'Diagonal move'),
('MoveDiagonal2', 'misc', 'Diagonal move variant'),
('MoveDown', 'misc', 'Move down'),
('MoveDownLeft', 'misc', 'Move down left'),
('MoveDownRight', 'misc', 'Move down right'),
('MoveHorizontal', 'misc', 'Move horizontal'),
('MoveLeft', 'misc', 'Move left'),
('MoveRight', 'misc', 'Move right'),
('MoveUp', 'misc', 'Move up'),
('MoveUpLeft', 'misc', 'Move up left'),
('MoveUpRight', 'misc', 'Move up right'),
('MoveVertical', 'misc', 'Move vertical'),
('Music2', 'music', 'Music variant 2'),
('Music3', 'music', 'Music variant 3'),
('Music4', 'music', 'Music variant 4'),
('Navigation2', 'navigation', 'Navigation variant'),
('Navigation2Off', 'navigation', 'Navigation 2 off'),
('NavigationOff', 'navigation', 'Navigation off'),
('Network', 'technology', 'Network'),
('Newspaper', 'media', 'Newspaper'),
('Nfc', 'technology', 'NFC technology'),
('NonBinary', 'people', 'Non-binary symbol'),
('Notebook', 'objects', 'Notebook'),
('NotebookPen', 'objects', 'Notebook with pen'),
('NotebookTabs', 'objects', 'Notebook with tabs'),
('NotebookText', 'objects', 'Notebook with text'),
('NotepadText', 'objects', 'Notepad text'),
('NotepadTextDashed', 'objects', 'Dashed notepad text'),
('Nut', 'objects', 'Nut fastener'),
('NutOff', 'objects', 'Nut off'),
('OctagonAlert', 'status', 'Octagon alert'),
('OctagonMinus', 'status', 'Octagon minus'),
('OctagonPause', 'status', 'Octagon pause'),
('OctagonX', 'status', 'Octagon X'),
('Omega', 'symbols', 'Omega symbol'),
('Option', 'misc', 'Option key'),
('Orbit', 'science', 'Orbital path'),
('Origami', 'objects', 'Origami'),
('Package2', 'objects', 'Package variant'),
('PackageCheck', 'objects', 'Package with check'),
('PackageMinus', 'objects', 'Package with minus'),
('PackageOpen', 'objects', 'Open package'),
('PackagePlus', 'objects', 'Package with plus'),
('PackageSearch', 'objects', 'Package search'),
('PackageX', 'objects', 'Package with X'),
('PaintBucket', 'tools', 'Paint bucket'),
('PaintRoller', 'tools', 'Paint roller'),
('Paintbrush', 'tools', 'Paintbrush'),
('PaintbrushVertical', 'tools', 'Vertical paintbrush'),
('Panda', 'animals', 'Panda'),
('PanelBottom', 'layout', 'Bottom panel'),
('PanelBottomClose', 'layout', 'Close bottom panel'),
('PanelBottomDashed', 'layout', 'Dashed bottom panel'),
('PanelBottomOpen', 'layout', 'Open bottom panel'),
('PanelLeft', 'layout', 'Left panel'),
('PanelLeftClose', 'layout', 'Close left panel'),
('PanelLeftDashed', 'layout', 'Dashed left panel'),
('PanelLeftOpen', 'layout', 'Open left panel'),
('PanelLeftRightDashed', 'layout', 'Dashed left right panel'),
('PanelRight', 'layout', 'Right panel'),
('PanelRightClose', 'layout', 'Close right panel'),
('PanelRightDashed', 'layout', 'Dashed right panel'),
('PanelRightOpen', 'layout', 'Open right panel'),
('PanelTop', 'layout', 'Top panel'),
('PanelTopBottomDashed', 'layout', 'Dashed top bottom panel'),
('PanelTopClose', 'layout', 'Close top panel'),
('PanelTopDashed', 'layout', 'Dashed top panel'),
('PanelTopOpen', 'layout', 'Open top panel'),
('PanelsLeftBottom', 'layout', 'Left bottom panels'),
('PanelsRightBottom', 'layout', 'Right bottom panels'),
('PanelsTopLeft', 'layout', 'Top left panels'),
('Parentheses', 'typography', 'Parentheses'),
('ParkingMeter', 'transportation', 'Parking meter'),
('PartyPopper', 'misc', 'Party popper'),
('PawPrint', 'animals', 'Paw print'),
('PcCase', 'technology', 'PC case'),
('Pen', 'tools', 'Pen'),
('PenLine', 'tools', 'Pen line'),
('PenOff', 'tools', 'Pen off'),
('Pencil', 'tools', 'Pencil'),
('PencilLine', 'tools', 'Pencil line'),
('PencilOff', 'tools', 'Pencil off'),
('PencilRuler', 'tools', 'Pencil with ruler'),
('Pentagon', 'shapes', 'Pentagon shape'),
('PersonStanding', 'people', 'Standing person'),
('PhilippinePeso', 'commerce', 'Philippine peso'),
('PhoneForwarded', 'communication', 'Forwarded phone'),
('PhoneMissed', 'communication', 'Missed phone call'),
('Pi', 'math', 'Pi symbol'),
('Piano', 'music', 'Piano'),
('Pickaxe', 'tools', 'Pickaxe'),
('PictureInPicture', 'media', 'Picture in picture'),
('PictureInPicture2', 'media', 'Picture in picture variant'),
('PiggyBank', 'commerce', 'Piggy bank'),
('Pilcrow', 'typography', 'Pilcrow symbol'),
('PilcrowLeft', 'typography', 'Left pilcrow'),
('PilcrowRight', 'typography', 'Right pilcrow'),
('Pill', 'medical', 'Pill medication'),
('PillBottle', 'medical', 'Pill bottle'),
('Pin', 'misc', 'Pin'),
('PinOff', 'misc', 'Pin off'),
('Pipette', 'tools', 'Pipette'),
('Pizza', 'food', 'Pizza'),
('Plane', 'transportation', 'Airplane'),
('PlaneLanding', 'transportation', 'Plane landing'),
('PlaneTakeoff', 'transportation', 'Plane takeoff'),
('Plug2', 'technology', 'Plug variant'),
('PlugZap', 'technology', 'Electric plug'),
('PocketKnife', 'tools', 'Pocket knife'),
('Podcast', 'media', 'Podcast'),
('Pointer', 'misc', 'Pointer'),
('PointerOff', 'misc', 'Pointer off'),
('Popcorn', 'food', 'Popcorn'),
('Popsicle', 'food', 'Popsicle'),
('PoundSterling', 'commerce', 'Pound sterling'),
('PowerOff', 'misc', 'Power off'),
('Presentation', 'misc', 'Presentation'),
('PrinterCheck', 'technology', 'Printer with check'),
('Projector', 'technology', 'Projector'),
('Proportions', 'misc', 'Proportions'),
('Puzzle', 'games', 'Puzzle piece'),
('Pyramid', 'shapes', 'Pyramid shape')

ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  updated_at = now();